version: '3.9'
services:
  db-config:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: sirius
    ports:
      - "3306:3306"
  db-mysql-tenant1:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: tenant1
    ports:
      - "3307:3306"
  db-mysql-tenant2:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: tenant2
    ports:
      - "3308:3306"